spring.datasource.url=jdbc:mysql://localhost:3306/CLIENT?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=looplock
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id = 539536405054-ab95ev2l17tn8r5mors1jmv8ppgn3ts5.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret = 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

logging.level.org.springframework.security = TRACE
