CREATE DATABASE IF NOT EXISTS db_looplock;
USE db_looplock;

CREATE TABLE IF NOT EXISTS credential (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(255) DEFAULT NULL,
    `password` VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(255) DEFAULT NULL,
    `password` VARCHAR(255) DEFAULT NULL
);